
about :

  name : wVocabulary
  description : Class to operate phrases. A phrase consists of words. Vocabulary enables the design of CLI based on phrases instead of words. It makes possible to group several similar phrases and help a user learn CLI faster. Use it to make your CLI more user-friendly.
  version : 0.3.41
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wVocabulary.git
  bugs : https://github.com/Wandalen/wVocabulary/issues
  entry.debug : '{path::out.debug}/dwtools/abase/____'
  entry.release : '{path::out.release}/dwtools/abase/____'

build :

  .debug.raw.export :
    default : 1
    filesPath : path::out.debug
    entryPath : path::entry.debug
    setting :
      debug : 1
      raw : 1
      export : 1
    steps :
      - build::.debug
      - step::export

  .release.compiled.export :
    filesPath : path::out.release
    entryPath : path::entry.release
    setting :
      debug : 0
      raw : 0
      export : 1
    steps :
      - build::.release.compiled
      - step::export

