

about :

  name : wVocabulary
  description : Class to operate phrases. A phrase consists of words. Vocabulary enables the design of CLI based on phrases instead of words. It makes possible to group several similar phrases and help a user learn CLI faster. Use it to make your CLI more user-friendly.
  version : 0.3.55
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wVocabulary.git
  bugs : https://github.com/Wandalen/wVocabulary/issues

build :

  debug.raw.export :
    exportDirPath : path::out.debug
    criterion :
      default : 1
      debug : 1
      raw : 1
      export : 1
      tar : 0
    steps :
      # - build::.debug.raw
      - step::export

  release.compiled.export :
    exportDirPath : path::out.release
    criterion :
      debug : 0
      raw : 0
      export : 1
      tar : 0
    steps :
      - build::release.compiled
      - step::export

  export.all :
    steps :
      - build::debug.raw.export
      - build::release.compiled.export

